# Generated by Django 5.1.3 on 2024-11-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwSecScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=32)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('ref_id', models.TextField()),
                ('result_link', models.TextField()),
                ('download_link', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
