# Generated by Django 5.1.3 on 2024-11-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sscs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SwSecScan',
            new_name='SoftwareSecurityScan',
        ),
    ]
